/* Sample data ported from the FOMO Padang prototype.
   Offsets >= 1000 mean "this weekend": 1000 = Saturday, 1001 = Sunday, 1003 = Saturday + 3.
   Marked as development sample content — replace with real Padang activities. */

export const SAMPLE_EVENTS = [
  {
    "slug": "padang-coffee-week-2026",
    "title": "Padang Coffee Week 2026",
    "description": "Tiga hari kumpul bareng roaster, barista, dan penikmat kopi se-Sumatera Barat. Ada cupping session kopi Solok Radjo dan Kerinci, manual brew bar, talkshow rantai pasok kopi, sampai live set akustik tiap sore. Bawa tumbler sendiri, ada diskon.",
    "category": "kuliner",
    "organizer": {
      "name": "Padang Coffee Community",
      "url": "https://instagram.com/padangcoffeecommunity"
    },
    "sourceUrl": "https://instagram.com/p/fomo-coffeeweek",
    "instagramUrl": "https://instagram.com/p/fomo-coffeeweek",
    "startOffset": 0,
    "endOffset": 2,
    "startTime": "15:00",
    "endTime": "22:00",
    "venueName": "Youth Center Padang",
    "address": "Jl. Rasuna Said, Padang Barat",
    "district": "Padang Barat",
    "latitude": -0.9438,
    "longitude": 100.3595,
    "priceType": "free",
    "priceAmount": null,
    "ticketUrl": null,
    "registrationRequired": false,
    "audience": "Semua Umur",
    "featured": true
  },
  {
    "slug": "indie-music-night-sumatra-sessions",
    "title": "Indie Music Night: Sumatra Sessions",
    "description": "Panggung kecil buat band lokal yang lagi ngumpulin lagu. Lima penampil, satu set akustik, kapasitas terbatas 120 orang. Tiket on the spot kalau masih ada slot.",
    "category": "musik",
    "organizer": {
      "name": "Rumah Kayu Collective",
      "url": "https://instagram.com/rumahkayucollective"
    },
    "sourceUrl": "https://instagram.com/p/fomo-sumatrasessions",
    "instagramUrl": "https://instagram.com/p/fomo-sumatrasessions",
    "startOffset": 0,
    "endOffset": 0,
    "startTime": "20:00",
    "endTime": "23:30",
    "venueName": "Rumah Kayu Coffee & Space",
    "address": "Jl. S. Parman No. 88, Ulak Karang",
    "district": "Padang Utara",
    "latitude": -0.9195,
    "longitude": 100.3532,
    "priceType": "paid",
    "priceAmount": 35000,
    "ticketUrl": "https://loket.example/sumatra-sessions",
    "registrationRequired": false,
    "audience": "Mahasiswa",
    "featured": false
  },
  {
    "slug": "bazar-umkm-ramai-ramai",
    "title": "Bazar UMKM Ramai-Ramai",
    "description": "Empat puluh pelaku UMKM Kota Padang buka lapak: makanan ringan, fesyen, kriya, sampai produk turunan gambir. Ada demo masak tiap jam 4 sore.",
    "category": "market",
    "organizer": {
      "name": "Dinas Koperasi & UKM Kota Padang",
      "url": "https://instagram.com/diskopukmpadang"
    },
    "sourceUrl": "https://instagram.com/p/fomo-bazarumkm",
    "instagramUrl": null,
    "startOffset": 0,
    "endOffset": 1,
    "startTime": "10:00",
    "endTime": "21:00",
    "venueName": "Plaza Andalas",
    "address": "Jl. Pemuda No. 21, Padang Barat",
    "district": "Padang Barat",
    "latitude": -0.9509,
    "longitude": 100.3583,
    "priceType": "free",
    "priceAmount": null,
    "ticketUrl": null,
    "registrationRequired": false,
    "audience": "Semua Umur",
    "featured": false
  },
  {
    "slug": "screening-film-pendek-lokal",
    "title": "Screening Film Pendek Lokal + Diskusi",
    "description": "Nonton bareng empat film pendek karya sineas Sumatera Barat, dilanjut diskusi santai bareng sutradara dan produsernya. Kapasitas 60 kursi, datang lebih awal.",
    "category": "seni",
    "organizer": {
      "name": "Ruang Kolektif Padang",
      "url": "https://instagram.com/ruangkolektifpadang"
    },
    "sourceUrl": "https://instagram.com/p/fomo-screening",
    "instagramUrl": "https://instagram.com/p/fomo-screening",
    "startOffset": 1,
    "endOffset": 1,
    "startTime": "19:00",
    "endTime": "22:00",
    "venueName": "Ruang Kolektif",
    "address": "Jl. Andalas No. 14, Simpang Haru",
    "district": "Padang Timur",
    "latitude": -0.9425,
    "longitude": 100.3861,
    "priceType": "free",
    "priceAmount": null,
    "ticketUrl": null,
    "registrationRequired": true,
    "audience": "Semua Umur",
    "featured": false
  },
  {
    "slug": "campus-career-fair-2026",
    "title": "Campus Career Fair 2026",
    "description": "Lebih dari 40 perusahaan buka booth rekrutmen: BUMN, startup, perbankan, sampai agensi kreatif. Bawa CV cetak minimal 10 rangkap. Ada sesi review CV gratis di lantai 2.",
    "category": "kampus",
    "organizer": {
      "name": "BEM Universitas Andalas",
      "url": "https://instagram.com/bemunand"
    },
    "sourceUrl": "https://instagram.com/p/fomo-careerfair",
    "instagramUrl": null,
    "startOffset": 2,
    "endOffset": 3,
    "startTime": "08:00",
    "endTime": "16:00",
    "venueName": "Auditorium Universitas Andalas",
    "address": "Kampus Limau Manis, Pauh",
    "district": "Pauh",
    "latitude": -0.9151,
    "longitude": 100.4618,
    "priceType": "free",
    "priceAmount": null,
    "ticketUrl": null,
    "registrationRequired": true,
    "audience": "Mahasiswa",
    "featured": true
  },
  {
    "slug": "diskusi-publik-mitigasi-bencana",
    "title": "Diskusi Publik: Mitigasi Bencana Kota Pesisir",
    "description": "Forum terbuka bareng BPBD, akademisi Unand, dan komunitas siaga bencana. Bahas jalur evakuasi baru, shelter, dan apa yang bisa disiapkan warga di tingkat RT.",
    "category": "pemerintahan",
    "organizer": {
      "name": "Pemerintah Kota Padang",
      "url": "https://padang.go.id"
    },
    "sourceUrl": "https://padang.go.id/agenda/mitigasi-2026",
    "instagramUrl": null,
    "startOffset": 2,
    "endOffset": 2,
    "startTime": "09:00",
    "endTime": "12:00",
    "venueName": "Balai Kota Padang",
    "address": "Jl. By Pass KM 12, Aie Pacah",
    "district": "Koto Tangah",
    "latitude": -0.8867,
    "longitude": 100.3833,
    "priceType": "free",
    "priceAmount": null,
    "ticketUrl": null,
    "registrationRequired": false,
    "audience": "Semua Umur",
    "featured": false
  },
  {
    "slug": "open-mic-night-kedai-sudut",
    "title": "Open Mic Night: Puisi, Stand Up, Musik",
    "description": "Panggung terbuka tiap Kamis. Daftar di tempat mulai jam 7, tampil 7 menit per orang. Bebas: baca puisi, stand up, atau bawa gitar.",
    "category": "musik",
    "organizer": {
      "name": "Kedai Sudut",
      "url": "https://instagram.com/kedaisudut.pdg"
    },
    "sourceUrl": "https://instagram.com/p/fomo-openmic",
    "instagramUrl": "https://instagram.com/p/fomo-openmic",
    "startOffset": 3,
    "endOffset": 3,
    "startTime": "20:00",
    "endTime": "23:00",
    "venueName": "Kedai Sudut",
    "address": "Jl. Gajah Mada No. 45, Siteba",
    "district": "Nanggalo",
    "latitude": -0.9095,
    "longitude": 100.3612,
    "priceType": "paid",
    "priceAmount": 20000,
    "ticketUrl": null,
    "registrationRequired": false,
    "audience": "Mahasiswa",
    "featured": false
  },
  {
    "slug": "workshop-membatik-tanah-liek",
    "title": "Workshop Membatik Tanah Liek",
    "description": "Belajar teknik batik tanah liek khas Minangkabau langsung dari pengrajin Kubang. Peserta membawa pulang satu kain hasil sendiri. Kuota 20 orang.",
    "category": "workshop",
    "organizer": {
      "name": "Museum Adityawarman",
      "url": "https://instagram.com/museumadityawarman"
    },
    "sourceUrl": "https://instagram.com/p/fomo-tanahliek",
    "instagramUrl": null,
    "startOffset": 4,
    "endOffset": 4,
    "startTime": "13:00",
    "endTime": "17:00",
    "venueName": "Museum Adityawarman",
    "address": "Jl. Diponegoro No. 10, Padang Barat",
    "district": "Padang Barat",
    "latitude": -0.9498,
    "longitude": 100.3573,
    "priceType": "paid",
    "priceAmount": 120000,
    "ticketUrl": "https://loket.example/tanah-liek",
    "registrationRequired": true,
    "audience": "Semua Umur",
    "featured": false
  },
  {
    "slug": "nobar-talkshow-bola-akar-rumput",
    "title": "Nobar + Talkshow: Bola Akar Rumput Sumbar",
    "description": "Nonton bareng laga malam, sebelumnya ada talkshow bareng pelatih SSB dan pengelola liga tarkam soal jalur pembinaan pemain muda di Sumbar.",
    "category": "komunitas",
    "organizer": {
      "name": "Komunitas Bola Padang",
      "url": "https://instagram.com/bolapadang"
    },
    "sourceUrl": "https://instagram.com/p/fomo-nobarbola",
    "instagramUrl": null,
    "startOffset": 4,
    "endOffset": 4,
    "startTime": "19:30",
    "endTime": "23:59",
    "venueName": "Youth Center Padang",
    "address": "Jl. Rasuna Said, Padang Barat",
    "district": "Padang Barat",
    "latitude": -0.9438,
    "longitude": 100.3595,
    "priceType": "free",
    "priceAmount": null,
    "ticketUrl": null,
    "registrationRequired": false,
    "audience": "Semua Umur",
    "featured": false
  },
  {
    "slug": "pasar-kreatif-padang",
    "title": "Pasar Kreatif Padang",
    "description": "Pasar akhir pekan buat brand lokal, ilustrator, dan penjual barang bekas pilihan. Ada zona thrift, zona kriya, dan panggung DJ set sore hari.",
    "category": "market",
    "organizer": {
      "name": "Kolektif Pasar Kreatif",
      "url": "https://instagram.com/pasarkreatifpdg"
    },
    "sourceUrl": "https://instagram.com/p/fomo-pasarkreatif",
    "instagramUrl": "https://instagram.com/p/fomo-pasarkreatif",
    "startOffset": 1000,
    "endOffset": 1001,
    "startTime": "10:00",
    "endTime": "18:00",
    "venueName": "Taman Imam Bonjol",
    "address": "Jl. Jend. Sudirman, Padang Barat",
    "district": "Padang Barat",
    "latitude": -0.9481,
    "longitude": 100.3616,
    "priceType": "free",
    "priceAmount": null,
    "ticketUrl": null,
    "registrationRequired": false,
    "audience": "Semua Umur",
    "featured": true
  },
  {
    "slug": "festival-kuliner-minang",
    "title": "Festival Kuliner Minang",
    "description": "Seratus lapak masakan Minang dari seluruh kota, dari rendang runtiah sampai sala lauak. Ada lomba masak randang antar kelurahan hari Minggu pagi.",
    "category": "kuliner",
    "organizer": {
      "name": "Dinas Pariwisata Kota Padang",
      "url": "https://instagram.com/pariwisatapadang"
    },
    "sourceUrl": "https://instagram.com/p/fomo-festkuliner",
    "instagramUrl": null,
    "startOffset": 1000,
    "endOffset": 1001,
    "startTime": "16:00",
    "endTime": "22:00",
    "venueName": "Pantai Padang (Taplau)",
    "address": "Jl. Samudera, Padang Barat",
    "district": "Padang Barat",
    "latitude": -0.954,
    "longitude": 100.352,
    "priceType": "free",
    "priceAmount": null,
    "ticketUrl": null,
    "registrationRequired": false,
    "audience": "Keluarga",
    "featured": true
  },
  {
    "slug": "futsal-community-cup",
    "title": "Futsal Community Cup",
    "description": "Turnamen antar komunitas, 16 tim, sistem gugur. Pendaftaran per tim, kuota tersisa 4 slot. Wajib bawa kartu identitas pemain.",
    "category": "olahraga",
    "organizer": {
      "name": "Padang Futsal League",
      "url": "https://instagram.com/padangfutsalleague"
    },
    "sourceUrl": "https://instagram.com/p/fomo-futsalcup",
    "instagramUrl": null,
    "startOffset": 1000,
    "endOffset": 1000,
    "startTime": "13:00",
    "endTime": "22:00",
    "venueName": "GOR Futsal Bandar Buat",
    "address": "Jl. Raya Indarung, Bandar Buat",
    "district": "Lubuk Kilangan",
    "latitude": -0.9787,
    "longitude": 100.4356,
    "priceType": "paid",
    "priceAmount": 250000,
    "ticketUrl": "https://wa.me/6281200000000",
    "registrationRequired": true,
    "audience": "Semua Umur",
    "featured": false
  },
  {
    "slug": "night-market-batang-arau",
    "title": "Night Market Batang Arau",
    "description": "Pasar malam di tepi sungai dengan latar bangunan kota tua. Jajanan kaki lima, live music, dan area duduk menghadap dermaga.",
    "category": "kuliner",
    "organizer": {
      "name": "Komunitas Kota Tua Padang",
      "url": "https://instagram.com/kotatuapadang"
    },
    "sourceUrl": "https://instagram.com/p/fomo-nightmarket",
    "instagramUrl": null,
    "startOffset": 1000,
    "endOffset": 1000,
    "startTime": "18:00",
    "endTime": "23:00",
    "venueName": "Kawasan Batang Arau",
    "address": "Jl. Batang Arau, Padang Selatan",
    "district": "Padang Selatan",
    "latitude": -0.97,
    "longitude": 100.361,
    "priceType": "free",
    "priceAmount": null,
    "ticketUrl": null,
    "registrationRequired": false,
    "audience": "Semua Umur",
    "featured": false
  },
  {
    "slug": "workshop-fotografi-analog",
    "title": "Workshop Fotografi Analog",
    "description": "Dasar-dasar kamera film: loading roll, metering manual, sampai proses cuci hitam putih di kamar gelap. Kamera analog disediakan untuk peserta yang belum punya.",
    "category": "workshop",
    "organizer": {
      "name": "Kubik Koffie & Darkroom",
      "url": "https://instagram.com/kubikkoffie"
    },
    "sourceUrl": "https://instagram.com/p/fomo-analog",
    "instagramUrl": "https://instagram.com/p/fomo-analog",
    "startOffset": 1001,
    "endOffset": 1001,
    "startTime": "09:00",
    "endTime": "14:00",
    "venueName": "Kubik Koffie",
    "address": "Jl. Veteran No. 27, Padang Barat",
    "district": "Padang Barat",
    "latitude": -0.9461,
    "longitude": 100.3629,
    "priceType": "paid",
    "priceAmount": 75000,
    "ticketUrl": "https://loket.example/analog",
    "registrationRequired": true,
    "audience": "Pelajar",
    "featured": false
  },
  {
    "slug": "padang-community-fun-run",
    "title": "Padang Community Fun Run 5K",
    "description": "Rute 5K menyusuri Pantai Padang sampai Muaro Lasak, start jam 6 pagi. Dapat jersey, medali finisher, dan sarapan. Kuota 500 pelari.",
    "category": "olahraga",
    "organizer": {
      "name": "Padang Runners",
      "url": "https://instagram.com/padangrunners"
    },
    "sourceUrl": "https://instagram.com/p/fomo-funrun",
    "instagramUrl": null,
    "startOffset": 1001,
    "endOffset": 1001,
    "startTime": "06:00",
    "endTime": "09:00",
    "venueName": "Muaro Lasak",
    "address": "Jl. Samudera, Purus, Padang Barat",
    "district": "Padang Barat",
    "latitude": -0.9482,
    "longitude": 100.3494,
    "priceType": "paid",
    "priceAmount": 50000,
    "ticketUrl": "https://loket.example/funrun",
    "registrationRequired": true,
    "audience": "Semua Umur",
    "featured": false
  },
  {
    "slug": "family-day-main-di-taman",
    "title": "Family Day: Main di Taman",
    "description": "Kegiatan gratis untuk anak dan orang tua: permainan tradisional, mendongeng, dan kelas melukis totebag. Bawa alas duduk sendiri.",
    "category": "keluarga",
    "organizer": {
      "name": "Ruang Main Padang",
      "url": "https://instagram.com/ruangmainpadang"
    },
    "sourceUrl": "https://instagram.com/p/fomo-familyday",
    "instagramUrl": null,
    "startOffset": 1001,
    "endOffset": 1001,
    "startTime": "07:30",
    "endTime": "11:00",
    "venueName": "Taman Melati",
    "address": "Jl. Jati Adabiah, Padang Timur",
    "district": "Padang Timur",
    "latitude": -0.9447,
    "longitude": 100.3742,
    "priceType": "free",
    "priceAmount": null,
    "ticketUrl": null,
    "registrationRequired": false,
    "audience": "Anak",
    "featured": false
  },
  {
    "slug": "pameran-seni-rupa-ombak-kedua",
    "title": "Pameran Seni Rupa \"Ombak Kedua\"",
    "description": "Pameran dua minggu dari 12 perupa Sumatera Barat yang membaca ulang hubungan kota Padang dengan lautnya. Ada artist talk tiap Sabtu sore.",
    "category": "seni",
    "organizer": {
      "name": "Taman Budaya Sumatera Barat",
      "url": "https://instagram.com/tamanbudayasumbar"
    },
    "sourceUrl": "https://instagram.com/p/fomo-ombakkedua",
    "instagramUrl": "https://instagram.com/p/fomo-ombakkedua",
    "startOffset": -2,
    "endOffset": 9,
    "startTime": "10:00",
    "endTime": "20:00",
    "venueName": "Galeri Taman Budaya Sumbar",
    "address": "Jl. Diponegoro No. 31, Padang Barat",
    "district": "Padang Barat",
    "latitude": -0.9512,
    "longitude": 100.3601,
    "priceType": "free",
    "priceAmount": null,
    "ticketUrl": null,
    "registrationRequired": false,
    "audience": "Semua Umur",
    "featured": false
  },
  {
    "slug": "kelas-menulis-esai-kota",
    "title": "Kelas Menulis: Esai Tentang Kota",
    "description": "Kelas menulis empat sesi untuk pemula. Sesi pertama membahas cara membaca kota sebagai bahan tulisan. Peserta menghasilkan satu esai 800 kata.",
    "category": "workshop",
    "organizer": {
      "name": "Ruang Kolektif Padang",
      "url": "https://instagram.com/ruangkolektifpadang"
    },
    "sourceUrl": "https://instagram.com/p/fomo-kelasmenulis",
    "instagramUrl": null,
    "startOffset": 1003,
    "endOffset": 1003,
    "startTime": "15:00",
    "endTime": "18:00",
    "venueName": "Perpustakaan Kota Padang",
    "address": "Jl. Sawahan No. 50, Padang Timur",
    "district": "Padang Timur",
    "latitude": -0.9414,
    "longitude": 100.3785,
    "priceType": "paid",
    "priceAmount": 60000,
    "ticketUrl": null,
    "registrationRequired": true,
    "audience": "Mahasiswa",
    "featured": false
  }
] as const;

export const SAMPLE_PLACES = [
  {
    "slug": "pantai-padang",
    "name": "Pantai Padang (Taplau)",
    "description": "Garis pantai sepanjang Jl. Samudera yang jadi ruang publik utama kota. Paling ramai menjelang matahari terbenam: pedagang jagung bakar, pukat nelayan, dan orang lari sore.",
    "tips": "Datang setelah jam 4 sore, parkir di sisi Muaro Lasak.",
    "address": "Jl. Samudera, Purus, Padang Barat",
    "district": "Padang Barat",
    "latitude": -0.954,
    "longitude": 100.352,
    "openingHours": "24 jam",
    "admissionType": "free",
    "admissionLabel": "Gratis",
    "instagramUrl": "https://instagram.com/pantaipadang",
    "websiteUrl": null
  },
  {
    "slug": "museum-adityawarman",
    "name": "Museum Adityawarman",
    "description": "Museum provinsi dengan koleksi benda budaya Minangkabau, dari kain songket sampai perlengkapan adat. Bangunannya sendiri rumah gadang bergonjong.",
    "tips": "Gratis untuk rombongan sekolah kalau ada surat pengantar.",
    "address": "Jl. Diponegoro No. 10, Padang Barat",
    "district": "Padang Barat",
    "latitude": -0.9498,
    "longitude": 100.3573,
    "openingHours": "Sel–Min, 08.00–16.00 · Senin tutup",
    "admissionType": "paid",
    "admissionLabel": "Rp5.000",
    "instagramUrl": "https://instagram.com/museumadityawarman",
    "websiteUrl": null
  },
  {
    "slug": "pantai-air-manis",
    "name": "Pantai Air Manis & Batu Malin Kundang",
    "description": "Pantai landai di balik Gunung Padang dengan formasi batu yang jadi latar legenda Malin Kundang. Air surut memungkinkan jalan kaki ke Pulau Pisang Ketek.",
    "tips": "Cek jadwal pasang surut kalau mau nyeberang ke Pulau Pisang Ketek.",
    "address": "Air Manis, Padang Selatan",
    "district": "Padang Selatan",
    "latitude": -0.9862,
    "longitude": 100.3617,
    "openingHours": "07.00–18.00",
    "admissionType": "paid",
    "admissionLabel": "Rp10.000",
    "instagramUrl": null,
    "websiteUrl": null
  },
  {
    "slug": "kota-tua-batang-arau",
    "name": "Kota Tua Batang Arau",
    "description": "Deretan gudang dan kantor dagang kolonial di tepi Sungai Batang Arau. Sekarang jadi kawasan kafe, mural, dan titik foto favorit akhir pekan.",
    "tips": "Paling enak jalan kaki dari Jembatan Siti Nurbaya ke arah muara.",
    "address": "Jl. Batang Arau, Padang Selatan",
    "district": "Padang Selatan",
    "latitude": -0.97,
    "longitude": 100.361,
    "openingHours": "24 jam (toko & kafe bervariasi)",
    "admissionType": "free",
    "admissionLabel": "Gratis",
    "instagramUrl": "https://instagram.com/kotatuapadang",
    "websiteUrl": null
  },
  {
    "slug": "taman-budaya-sumbar",
    "name": "Taman Budaya Sumatera Barat",
    "description": "Kompleks kesenian dengan galeri, teater terbuka, dan ruang latihan. Hampir tiap minggu ada pameran, pertunjukan tari, atau latihan teater yang boleh ditonton.",
    "tips": "Cek papan agenda di pintu masuk, banyak acara yang tidak diumumkan online.",
    "address": "Jl. Diponegoro No. 31, Padang Barat",
    "district": "Padang Barat",
    "latitude": -0.9512,
    "longitude": 100.3601,
    "openingHours": "Sen–Sab, 08.00–20.00",
    "admissionType": "free",
    "admissionLabel": "Gratis",
    "instagramUrl": "https://instagram.com/tamanbudayasumbar",
    "websiteUrl": null
  },
  {
    "slug": "gunung-padang-siti-nurbaya",
    "name": "Gunung Padang & Makam Siti Nurbaya",
    "description": "Bukit di mulut Batang Arau dengan anak tangga menuju puncak. Titik pandang terbaik untuk melihat kota, pelabuhan, dan garis pantai sekaligus.",
    "tips": "Naik pagi atau sore, tangganya terbuka dan panas di siang hari.",
    "address": "Batang Arau, Padang Selatan",
    "district": "Padang Selatan",
    "latitude": -0.9757,
    "longitude": 100.3616,
    "openingHours": "07.00–18.00",
    "admissionType": "paid",
    "admissionLabel": "Rp5.000",
    "instagramUrl": null,
    "websiteUrl": null
  },
  {
    "slug": "hutan-mangrove-bungus",
    "name": "Hutan Mangrove Bungus",
    "description": "Jalur kayu menyusuri mangrove di teluk selatan kota. Tenang, cocok untuk jalan pagi, mengamati burung, dan menyewa perahu kecil ke pulau kecil sekitar.",
    "tips": "Bawa lotion anti nyamuk, dan tawar harga perahu sebelum naik.",
    "address": "Bungus Teluk Kabung",
    "district": "Bungus Teluk Kabung",
    "latitude": -1.045,
    "longitude": 100.393,
    "openingHours": "08.00–17.00",
    "admissionType": "paid",
    "admissionLabel": "Rp10.000",
    "instagramUrl": null,
    "websiteUrl": null
  },
  {
    "slug": "taman-imam-bonjol",
    "name": "Taman Imam Bonjol",
    "description": "Taman kota di jantung Padang, tempat komunitas latihan tiap sore: skateboard, dance, sampai kelas bahasa gratis. Ada lapangan basket dan jalur lari pendek.",
    "tips": "Sabtu pagi biasanya ada car free day di sepanjang Jl. Sudirman.",
    "address": "Jl. Jend. Sudirman, Padang Barat",
    "district": "Padang Barat",
    "latitude": -0.9481,
    "longitude": 100.3616,
    "openingHours": "24 jam",
    "admissionType": "free",
    "admissionLabel": "Gratis",
    "instagramUrl": null,
    "websiteUrl": null
  }
] as const;
